apiVersion: apps/v1
kind: Deployment
metadata:
  name: mando-app
  labels:
    app: mando
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mando
  template:
    metadata:
      labels:
        app: mando
    spec:
      containers:
      - name: mando
        image: tanzu-harbor.pngd.gob.pe/mef-ped-prod/cards:latest
        ports:
        - containerPort: 8501
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: mando-service
spec:
  selector:
    app: mando
  ports:
    - protocol: TCP
      port: 8501
      targetPort: 8501
  type: ClusterIP
